name: Build and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main

      - name: Setup Python ⬇️
        uses: actions/setup-python@v3

      - name: Install MkDocs ⬇️
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions pygments

      - name: Building book ⚙️
        run: |
          python -m mkdocs build --verbose --clean

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: site
